# Generated by Django 5.2.15 on 2026-07-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.CharField(max_length=30)),
                ('female', models.CharField(max_length=30)),
                ('relationship_status', models.CharField(max_length=20)),
                ('common_intrest', models.TextField()),
                ('fav_spots', models.TextField()),
            ],
        ),
    ]
