# Generated by Django 5.2.15 on 2026-07-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couple',
            old_name='common_intrest',
            new_name='common_interest',
        ),
    ]
